//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfVideoKlub
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VideoKlubEntities : DbContext
    {
        public VideoKlubEntities()
            : base("name=VideoKlubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clan> Clans { get; set; }
        public virtual DbSet<Film> Films { get; set; }
        public virtual DbSet<Iznajmljivanje> Iznajmljivanjes { get; set; }
    
        public virtual ObjectResult<PrikaziIznajmljivanja_Result> PrikaziIznajmljivanja()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PrikaziIznajmljivanja_Result>("PrikaziIznajmljivanja");
        }
    }
}
